notifications:
    email: true

env:
    - UTIL=ansible-playbook VERSION=$(curl -s https://pypi.python.org/pypi/ansible/json|jq --raw-output ".info.version")

before_install:
    - sudo apt-get install -y jq

install:
    - cd ${UTIL} && docker build -t ${UTIL}:${TRAVIS_COMMIT} -f Dockerfile .

script:
    - docker run ${UTIL}:${TRAVIS_COMMIT} --version |grep ${VERSION}

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        docker tag -f ${UTIL}:${TRAVIS_COMMIT} ${DOCKER_REPOSITORY}/${UTIL}:latest;
        docker push ${DOCKER_REPOSITORY}/${UTIL}:latest;
      fi
