notifications:
    email: true

env:
    - UTIL=ansible-playbook VERSION_CHECK="--version"
    - UTIL=kubectl          VERSION_CHECK="version --client"

install:
    - cd ${UTIL} && docker build -t ${UTIL}:${TRAVIS_COMMIT} -f Dockerfile .

script:
    - docker run ${UTIL}:${TRAVIS_COMMIT} ${VERSION_CHECK}

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        docker tag ${UTIL}:${TRAVIS_COMMIT} ${DOCKER_REPOSITORY}/${UTIL}:latest;
        docker push ${DOCKER_REPOSITORY}/${UTIL}:latest;
      fi
