notifications:
    email: true

env:
    - UTIL=ansible-playbook 

before_install:
    - sudo apt-get install -y jq

install:
    - cd ${UTIL} && docker build -t ${UTIL}:${TRAVIS_COMMIT} -f Dockerfile .

script:
    - docker run ${UTIL}:${TRAVIS_COMMIT} --version 
